name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.c88f427f-4597-407b-8bfa-436ca6af2b1a}}
          heroku_app_name: "github-actions"
          heroku_email: "mmoghal29@gmail.com"
